### ISSUE TITLE
Dark Mode support

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/jessesquires.com#89]
**EDIT:**

It looks like eventually bootstrap will support this:
https://github.com/twbs/bootstrap/issues/27514

------

https://kevinchen.co/blog/support-macos-mojave-dark-mode-on-websites/

example:
https://github.com/SwiftWeekly/swiftweekly.github.io/commit/b78a750ef57b9b2a3a03d57694197ea0822dbbe3

Will also need to address #58 as part of this.

- https://github.com/vinorodrigues/bootstrap-dark-5
- https://github.com/vinorodrigues/bootstrap-dark

**Comment by jessesquires** [comment]
A basic proof of concept:

#### in the `<head>`

```html
<meta name="color-scheme" content="light dark">
```

#### sass

```css
body {
    @media (prefers-color-scheme: dark) {
        background-color: $dark;
        color: $light;
     }
}

```
